package am2.preloader;

import am2.LogHelper;
import am2.common.AM2EnviromentData;
import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;

import java.io.File;
import java.util.Arrays;
import java.util.Map;


public class AM2PreloaderContainer extends DummyModContainer implements IFMLLoadingPlugin{

	private final String[] asmTransformers = new String[]{"am2.preloader.AccessTransformers", "am2.preloader.BytecodeTransformers"};
	private final ModMetadata md = new ModMetadata();

	public AM2PreloaderContainer(){
		LogHelper.info("Core initializing...stand back!  I'm going to try MAGIC!");

		md.autogenerated = true;
		md.credits = "Mithion, AlgorithmX2, Sunstrike";
		md.modId = getModId();
		md.version = getVersion();
		md.name = getName();
		md.authorList = Arrays.asList("Mithion", "AlgorithmX2", "Sunstrike");
	}

	@Override
	public String getModId(){
		return "AM2-Preloader";
	}

	@Override
	public String getName(){
		return "AMCore";
	}

	@Override
	public String getVersion(){
		return "0.0.3";
	}

	@Override
	public String getDisplayVersion(){
		return getVersion();
	}

	@Override
	public ModMetadata getMetadata(){
		return md;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller){
		bus.register(this);
		return true;
	}

	@Override
	public String[] getASMTransformerClass(){
		return asmTransformers;
	}

	@Override
	public String getModContainerClass(){
		return "am2.preloader.AM2PreloaderContainer";
	}

	@Override
	public String getSetupClass(){
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data){
		// This is very crude check for mods presence using filename.
		// Some mods may refer to others in their name, so we'll to confirm those assumption with class presence check.
		File loc = (File)data.get("mcLocation");

		LogHelper.trace("MC located at: " + loc.getAbsolutePath());
		AM2EnviromentData.isDevEnvironment = !(Boolean)data.get("runtimeDeobfuscationEnabled");

		File mcFolder = new File(loc.getAbsolutePath() + File.separatorChar + "mods");
		File[] subfiles = mcFolder.listFiles();
		for (File file : subfiles){
			String name = file.getName();
			if (name != null) {
				name = name.toLowerCase();
				if (name.endsWith(".jar") || name.endsWith(".zip")){
					if (name.contains("thaumcraft")){
						LogHelper.info("Core: Located Thaumcraft in " + file.getName());
						AM2EnviromentData.foundThaumcraft = true;
					}else if (name.contains("optifine")){
						LogHelper.info("Core: Located OptiFine in " + file.getName() + ". We'll to confirm that...");
						AM2EnviromentData.foundOptiFine = true;
					}else if (name.contains("dragonapi")){
						LogHelper.info("Core: Located DragonAPI in " + file.getName());
						AM2EnviromentData.foundDragonAPI = true;
					}
				}
			}
		}
	}

	@Override
	public String getAccessTransformerClass(){
		return null;
	}

	public static boolean isOptiFinePresent(){
		if (!AM2EnviromentData.confirmedOptiFine && AM2EnviromentData.foundOptiFine){
			// Check presence of OptiFine core classes
			try{
				Class.forName("optifine.OptiFineForgeTweaker");
			}
			catch (ClassNotFoundException exception1){
				try{
					Class.forName("optifine.OptiFineTweaker");
				}
				catch (ClassNotFoundException exception2){
					AM2EnviromentData.foundOptiFine = false;
				}
			}
			if (AM2EnviromentData.foundOptiFine){
				LogHelper.info("Core: OptiFine presence has been confirmed.");
			} else {
				LogHelper.info("Core: OptiFine doesn't seem to be there actually.");
			}
			AM2EnviromentData.confirmedOptiFine = true;
		}
		return AM2EnviromentData.foundOptiFine;
	}
}
